// Snapshot do catálogo anterior à F7; revisão editorial e licença pendentes.
export const talentosOrigem2024 = [
  { nome: "Alerta", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: null, condicao: null, bonus: null, valor: null }], descricao: "Você ganha prontidão excepcional para agir no começo de um combate." },
  { nome: "Artifista", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: null, condicao: null, bonus: null, valor: null }], descricao: "Você domina ferramentas e cria itens com eficiência durante descansos." },
  { nome: "Atacante Selvagem", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: null, condicao: null, bonus: null, valor: null }], descricao: "Você causa ferimentos mais devastadores com seus ataques com arma." },
  { nome: "Curandeiro", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: null, condicao: null, bonus: null, valor: null }], descricao: "Você sabe estabilizar aliados e potencializar cuidados médicos." },
  { nome: "Habilidoso", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: null, condicao: null, bonus: null, valor: null }], descricao: "Você recebe treinamento adicional em perícias ou ferramentas." },
  { nome: "Iniciado em Magia (Clérigo)", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: "magia", condicao: null, bonus: ["magias iniciais"], valor: 1 }], descricao: "Você aprende magias iniciais associadas à lista de Clérigo." },
  { nome: "Iniciado em Magia (Druida)", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: "magia", condicao: null, bonus: ["magias iniciais"], valor: 1 }], descricao: "Você aprende magias iniciais associadas à lista de Druida." },
  { nome: "Iniciado em Magia (Mago)", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: "magia", condicao: null, bonus: ["magias iniciais"], valor: 1 }], descricao: "Você aprende magias iniciais associadas à lista de Mago." },
  { nome: "Músico", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: null, condicao: null, bonus: null, valor: null }], descricao: "Você inspira aliados com música ao final de descansos." },
  { nome: "Sortudo", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: null, condicao: null, bonus: null, valor: null }], descricao: "Você possui pontos de sorte para influenciar testes, ataques ou salvaguardas." },
  { nome: "Valentão de Taverna", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: null, condicao: null, bonus: null, valor: null }], descricao: "Você é eficiente em combate improvisado e brigas de curta distância." },
  { nome: "Vigoroso", categoria: "Origin", requisito: { tipo: null, requisito: null, valor: null }, bonus: [{ tipo: null, condicao: null, bonus: null, valor: null }], descricao: "Você recebe resistência adicional para suportar perigos." }
];
